# Generated by Django 2.1.4 on 2018-12-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasadelaAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturaa',
            options={'verbose_name': 'Factura Contrato', 'verbose_name_plural': 'Facturas Contratos'},
        ),
        migrations.AlterModelOptions(
            name='facturae',
            options={'verbose_name': 'Factura Electrica', 'verbose_name_plural': 'Facturas Electricas'},
        ),
        migrations.AddField(
            model_name='contrato',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='facturaa',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='facturae',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
