# Generated by Django 2.1.4 on 2018-12-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasadelaAPI', '0003_factura_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
    ]
